"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var NonPromitives;
(function (NonPromitives) {
    NonPromitives["username"] = "username";
    NonPromitives["name"] = "name";
    NonPromitives["firstname"] = "firstname";
    NonPromitives["lastname"] = "lastname";
    NonPromitives["email"] = "email";
    NonPromitives["word"] = "word";
    NonPromitives["words"] = "words";
    NonPromitives["title"] = "title";
    NonPromitives["text"] = "text";
    NonPromitives["sentence"] = "sentence";
    NonPromitives["sentences"] = "sentences";
    NonPromitives["paragraph"] = "paragraph";
    NonPromitives["paragraphs"] = "paragraphs";
    NonPromitives["uuid"] = "uuid";
    NonPromitives["age"] = "age";
    NonPromitives["age18"] = "age18";
})(NonPromitives = exports.NonPromitives || (exports.NonPromitives = {}));
