export enum NonPromitives {
    username = "username",
    name = "name",
    firstname = "firstname",
    lastname = "lastname",
    email = "email",
    word = "word",
    words = "words",
    title = "title",
    text = "text",
    sentence = "sentence",
    sentences = "sentences",
    paragraph = "paragraph",
    paragraphs = "paragraphs",
    uuid = "uuid",
    age = "age",
    age18 = "age18",
}